---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: service-discovery-release

params: []

run:
  path: service-discovery-release/ci/tasks/test-acceptance.sh
