---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

inputs:
  - name: container-networking-ci

params:
  API: ~
  ADMIN_USER: admin
  ADMIN_PASSWORD: ~
  ORG_NAME: test-users
  SPACE_NAME: ~
  USER: ~

run:
  path: container-networking-ci/tasks/add-space-developer
