---
platform: linux

image_resource:
  type: docker-image
  source: {repository: alpine}

inputs:
- name: golang-1.x-tarball
- name: dockerfile

outputs:
- name: docker-build-context

params:
  INPUT_DOCKERFILE_PATH: Dockerfile

run:
  path: bash
  args:
  - -exuc
  - |
    cp $INPUT_DOCKERFILE_PATH context/
    cp golang-1.x-tarball/go* context/
