---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking-ci
  - name: cf-networking

outputs:
  - name: binaries

run:
  path: cf-networking-ci/tasks/build-cli
