---
platform: linux

image_resource:
  type: docker-image
  source: { repository: golang }

inputs:
  - name: ducatify

outputs:
  - name: ducatify-bin

run:
  path: /bin/bash
  args:
    - -c
    - |
      set -e
      set -x
      set -u
      mkdir -p $GOPATH/src/github.com/cloudfoundry-incubator/
      cp -R $PWD/ducatify $GOPATH/src/github.com/cloudfoundry-incubator/
      go build -o ducatify-bin/ducatify github.com/cloudfoundry-incubator/ducatify/cmd/ducatify
