---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

platform: linux

inputs:
  - name: container-networking-ci
  - name: deployments-repo
  - name: cf-deployment

run:
  path: container-networking-ci/tasks/cf-deployment

params:
  ENVIRONMENT_NAME: ~
  MANIFEST_FILE: ~
