#!/bin/bash

set -e -x -u

pushd deployments-repo/environments/$ENVIRONMENT_NAME
  export BOSH_DIRECTOR_URL=$(bbl director-address)
  export BOSH_PASSWORD=$(bbl director-password)
  export BOSH_USER=$(bbl director-username)
  bbl director-ca-cert > /tmp/ca.crt
popd

env

# TEMP PATCH
pushd cf-deployment
  git apply ../container-networking-ci/netman-cf-deployment.patch
popd

VAR_FILE=${PWD}/deployments-repo/environments/${ENVIRONMENT_NAME}/deployment-env-vars.yml

bosh-cli -d cf -e $BOSH_DIRECTOR_URL --ca-cert=/tmp/ca.crt -n deploy --var-files=${VAR_FILE} ${MANIFEST_FILE}
