#!/bin/bash
# vim: set ft=sh

set -e -x -u

BIN_DIR=/tmp/bin
mkdir -p ${BIN_DIR}

export GOPATH=/tmp/go
mkdir -p $GOPATH

export PATH=$PATH:$BIN_DIR:$GOPATH

# install bbl
curl -o ${BIN_DIR}/bbl -L https://github.com/cloudfoundry/bosh-bootloader/releases/download/v1.1.0/bbl-v1.1.0_linux_x86-64
chmod +x ${BIN_DIR}/bbl

# install bosh-init
curl -o ${BIN_DIR}/bosh-init -L https://s3.amazonaws.com/bosh-init-artifacts/bosh-init-0.0.98-linux-amd64
chmod +x ${BIN_DIR}/bosh-init

# install bosh-cli
go get github.com/cloudfoundry/bosh-cli

pushd deployments-repo/environments/$ENVIRONMENT_NAME
  export BOSH_DIRECTOR_URL=$(bbl director-address)
  export BOSH_PASSWORD=$(bbl director-password)
  export BOSH_USER=$(bbl director-username)
  bbl director-ca-cert > /tmp/ca.crt
popd

env

# TEMP PATCH
pushd cf-deployment
  git apply ../container-networking-ci/netman-cf-deployment.patch
popd

VAR_FILE=${PWD}/deployments-repo/environment/${ENVIRONMENT_NAME}/deployment-env-vars.yml

bosh-cli -d cf -e $BOSH_DIRECTOR_URL --ca-cert=/tmp/ca.crt -n deploy --var-files=${VAR_FILE} ${MANIFEST_FILE}
