---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

platform: linux

inputs:
  - name: cf-networking

run:
  path: cf-networking-ci/tasks/check-empty-networking-opsfile
