#!/bin/bash

set -e -u

pushd "cf-networking"
  if [ ! -d "manifest-generation/opsfiles/experimental" ] ; then
    exit 1
  fi

  let non_comment_lines=$(cat manifest-generation/opsfiles/experimental/* | grep -Ecv '^#')
  if [ "$non_comment_lines" -gt "0" ]; then
    echo "additions in experimental opsfiles should be merged in cf-deployment before shipping"
    exit 1
  fi
popd
