---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

inputs:
  - name: cf-networking-ci
  - name: cf-networking

run:
  path: cf-networking-ci/tasks/check-empty-networking-opsfile
