---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

params:
  ENVIRONMENT: ~

inputs:
  - name: container-networking-deployments

outputs:
  - name: integration-config

run:
  path: container-networking-ci/tasks/copy-config
