#!/bin/bash

set -e

# replace admin password in test config
pushd container-networking-deployments/environments/${ENVIRONMENT}
  ADMIN_PASSWORD=`grep uaa_scim_users_admin_password vars-store.yml  | cut -d' ' -f2`
  sed -i -- "s/{{admin-password}}/${ADMIN_PASSWORD}/g" integration_config.json
popd

cp container-networking-deployments/environments/${ENVIRONMENT}/integration_config.json integration-config/
