---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

params:
  ENVIRONMENT: ~

inputs:
  - name: container-networking-deployments

outputs:
  - name: integration-config

run:
  path: sh
  args:
  - -exc
  - |
    cp container-networking-deployments/environments/${ENVIRONMENT}/integration_config.json integration-config/
