---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

params: {}

inputs:
  - name: garden-runc-release

outputs:
  - name: garden-runc-release-tarball

run:
  path: bash
  args:
    - -c
    - |
       (cd garden-runc-release && bosh sync blobs ) \
       && bosh create release --version $(date "+%s") --with-tarball --name garden-runc --dir garden-runc-release \
       && cp garden-runc-release/dev_releases/garden-runc/*.tgz garden-runc-release-tarball
