---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

platform: linux

inputs:
  - name: cf-networking-ci
  - name: deployments-repo

run:
  path: cf-networking-ci/tasks/create-apps-domain

params:
  ENVIRONMENT_NAME: ~
  NEW_APPS_DOMAIN: ~
