---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/ducati-deploy }

platform: linux

params: {}

inputs:
  - name: cf-release

outputs:
  - name: cf-release-tarball

run:
  path: bash
  args:
    - -c
    - |
      ( cd cf-release && for i in {1..5}; do bosh -n --parallel 5 sync blobs && break; done ) \
       && bosh create release --version $(date "+%s") --with-tarball --name cf-release --dir cf-release \
       && cp cf-release/dev_releases/cf-release/*.tgz cf-release-tarball
