#!/bin/bash

set -e -u
set -o pipefail

system_domain="${ENVIRONMENT_NAME}.c2c.cf-app.com"

pushd "deployments-repo/environments/${ENVIRONMENT_NAME}"
  admin_password=`grep scim vars-store.yml  | cut -d' ' -f2`
popd

cf api api.$system_domain --skip-ssl-validation
cf auth admin $admin_password

set +e
echo "try to create shared domain, but ignore error (e.g. if it already exists)"
cf create-shared-domain $NEW_APPS_DOMAIN || true
