---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: cf-networking-ci
  - name: cli-plugin-fork

run:
  path: cf-networking-ci/tasks/create-plugin-pr
