---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

params:
  BOSH_TARGET: ~
  BOSH_USER: admin
  BOSH_PASSWORD: ~
  DEPLOYMENT_NAME: ~

run:
  path: /bin/bash
  args:
    - -c
    - |
      bosh target $BOSH_TARGET
      bosh -n delete deployment $DEPLOYMENT_NAME --force
