platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

inputs:
  - name: container-networking-ci

run:
  path: container-networking-ci/tasks/emit-datadog-event

params:
  TITLE:
  TEXT:
  PRIORITY:
  AWS_ENV:
  DATADOG_API_KEY:
