---
platform: windows

inputs:
  - name: ci
  - name: cf-networking-release

run:
  path: powershell
  args:
    - "-ExecutionPolicy"
    - "Bypass"
    - "-File"
    - ci/tasks/garden-external-networker-windows.ps1
