#!/bin/bash

set -e -u

pushd deployments-repo/environments/$ENVIRONMENT_NAME
  export BOSH_DIRECTOR_URL=$(bbl director-address)
  export BOSH_PASSWORD=$(bbl director-password)
  export BOSH_USER=$(bbl director-username)
  bbl director-ca-cert > /tmp/ca.crt
popd

VAR_FILE=deployments-repo/environments/${ENVIRONMENT_NAME}/deployment-env-vars.yml
MANIFEST_FILE=cf-deployment/cf-deployment.yml
DIRECTOR_UUID=$(curl -s -k $BOSH_DIRECTOR_URL/info | jq -r .uuid)

function makeManifest() {
  outFile=$1
  bosh-cli -d cf -e $BOSH_DIRECTOR_URL --ca-cert=/tmp/ca.crt build-manifest --var-files=${VAR_FILE} ${MANIFEST_FILE} > $outFile
  echo "director_uuid: ${DIRECTOR_UUID}" >> $outFile
}

makeManifest deployment-manifests/plain.yml

pushd cf-deployment
  git apply ../container-networking-ci/netman-cf-deployment.patch
popd

makeManifest deployment-manifests/with-netman.yml
