#!/bin/bash

set -e -u

pushd deployments-repo/environments/$ENVIRONMENT_NAME
  export BOSH_ENVIRONMENT=$(bbl director-address)
  bbl director-ca-cert > /tmp/ca.crt
  export BOSH_CA_CERT=/tmp/ca.crt
popd

VARS_STORE=deployments-repo/environments/${ENVIRONMENT_NAME}/vars-store.yml
MANIFEST_FILE=cf-deployment/cf-deployment.yml
CF_NETWORKING_OPS_FILE=cf-networking/manifest-generation/opsfiles/cf-networking.yml
AWS_OPS_FILE=cf-deployment/operations/change-logging-port-for-aws-elb.yml
ENVIRONMENT_OPS_FILE=deployments-repo/environments/${ENVIRONMENT_NAME}/opsfile.yml

function makeManifest() {
  outFile=$1
  bosh-cli interpolate --var-errs \
    --vars-store=${VARS_STORE} \
    -o ${AWS_OPS_FILE} \
    -o ${CF_NETWORKING_OPS_FILE} \
    -o ${ENVIRONMENT_OPS_FILE} \
    ${MANIFEST_FILE} > $outFile
}

echo "Making manifest"
makeManifest deployment-manifest/cf.yml


echo "Checking for updates to vars store"
pushd deployments-repo/environments/$ENVIRONMENT_NAME

  # `|| true` because grep returns with exit status 1 if nothing is found
  CHANGED=`git ls-files -m | grep vars-store.yml || true`
  echo ${CHANGED}

  if [[ ! -z $CHANGED ]]; then
    echo "Committing changes to vars store"
    git config --global user.email "container-networking+ci@pivotal.io"
    git config --global user.name "Container Networking Bot"

    git add vars-store.yml
    git commit -m "[${ENVIRONMENT_NAME}] update vars store"
  fi
popd

git clone deployments-repo deployments-repo-output

echo "Done"
