---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

platform: linux

inputs:
  - name: container-networking-ci
  - name: deployments-repo
  - name: cf-deployment
outputs:
  - name: deployment-manifests

run:
  path: container-networking-ci/tasks/generate-upgrade-manifests

params:
  ENVIRONMENT_NAME: ~
