#!/bin/bash

set -e -x -u

# environment_path="${PWD}/deployments-repo/environments/${ENVIRONMENT_NAME}"
environment_path="${PWD}/container-networking-deployments/environments/${ENVIRONMENT_NAME}"
output_path=${PWD}/generated-manifest
diego_release_path=${PWD}/diego-release
stubs_path="${PWD}/container-networking-ci/stubs/diego"

pushd cf-release
  ./scripts/generate_deployment_manifest aws \
    ${environment_path}/stubs/director-uuid.yml \
    ${diego_release_path}/examples/aws/stubs/cf/diego.yml \
    ${environment_path}/stubs/cf/properties.yml \
    ${environment_path}/stubs/cf/instance-count-overrides.yml \
    ${environment_path}/stubs/cf/stub.yml \
    > ${output_path}/cf.yml
popd

sed "s/\ CELL_Z1_COUNT/\ ${CELL_COUNT}/" < ${stubs_path}/instance_count_overrides.yml > ${stubs_path}/instance_count_overrides1.yml

pushd diego-release
  ./scripts/generate-deployment-manifest \
    -g \
    -c ${output_path}/cf.yml \
    -i ${environment_path}/stubs/diego/iaas-settings.yml \
    -p ${environment_path}/stubs/diego/property-overrides.yml \
    -n ${stubs_path}/instance_count_overrides1.yml \
    -v ${environment_path}/stubs/diego/release-versions.yml \
    > ${output_path}/diego0.yml
popd

sed 's/\ guardian/\ garden-runc/' < ${output_path}/diego0.yml > ${output_path}/diego1.yml

pushd netman-release
  ./scripts/netmanify \
    ${output_path}/diego1.yml \
    ${environment_path}/stubs/netman/cf_creds_stub.yml \
    ${environment_path}/stubs/cf/stub.yml \
    > ${output_path}/diego.yml
popd
