#!/bin/bash

set -e -x -u

environment_path="${PWD}/deployments-repo/environments/${ENVIRONMENT_NAME}"
output_path=${PWD}/generated-manifest
diego_release_path=${PWD}/diego-release

pushd cf-release
  ./scripts/generate_deployment_manifest aws \
    ${environment_path}/stubs/director-uuid.yml \
    ${diego_release_path}/examples/aws/stubs/cf/diego.yml \
    ${environment_path}/stubs/cf/properties.yml \
    ${environment_path}/stubs/cf/instance-count-overrides.yml \
    ${environment_path}/stubs/cf/stub.yml \
    > ${output_path}/cf.yml
popd

pushd diego-release
  ./scripts/generate-deployment-manifest \
    -g \
    -c ${output_path}/cf.yml \
    -i ${environment_path}/stubs/diego/iaas-settings.yml \
    -p ${environment_path}/stubs/diego/property-overrides.yml \
    -n ${environment_path}/stubs/diego/instance-count-overrides.yml \
    -v ${environment_path}/stubs/diego/release-versions.yml \
    > ${output_path}/diego0.yml
popd

sed 's/guardian-release/garden-runc-release/' < ${output_path}/diego0.yml > ${output_path}/diego1.yml

ducatify-bin/ducatify \
  --diego ${output_path}/diego1.yml \
  --cfCreds ${environment_path}/stubs/ducati/cf_creds_stub.yml \
  > ${output_path}/diego.yml
