---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/small-git }

inputs:
  - name: updated-integration-configs

outputs:
  - name: integration-config-with-cf-networking

run:
  path: /bin/bash
  args:
    - -c
    - |
      cat updated-integration-configs/environments/trucker/integration_config.json | \
      jq ".include_container_networking=true" | \
      jq ".include_diego_ssh=false" | \
      jq ".include_internet_dependent=false" | \
      jq ".include_routing=false" \
      > integration-config-with-cf-networking/integration_config.json
