---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: container-networking-ci
  - name: netman-release-dev
  - name: netman-release-master

outputs:
  - name: release-merged

run:
  path: container-networking-ci/tasks/merge-master
