#!/bin/bash

set -e

ENVIRONMENT_PATH="test-config/environments/${ENVIRONMENT_NAME}/netman-cf-acceptance.json"
export CONFIG=${PWD}/${CONFIG:-"${ENVIRONMENT_PATH}"}

echo $CONFIG

export NETWORK_STATS_FILE=$PWD/network-stats/stats.json

cd netman-release
export GOPATH=$PWD

go build -o /tmp/bin/network-policy-plugin ./src/cli-plugin
cf install-plugin -f /tmp/bin/network-policy-plugin

cd src/netman-cf-acceptance
export APPS_DIR=../example-apps
ginkgo -r -v
