#!/bin/bash

set -e

# replace admin password in test config
pushd test-config/environments/${ENVIRONMENT_NAME}
  ADMIN_PASSWORD=`grep uaa_scim_users_admin_password vars-store.yml  | cut -d' ' -f2`
  sed -i -- "s/REPLACE_ADMIN_PASSWORD/${ADMIN_PASSWORD}/g" netman-cf-acceptance.json
popd

ENVIRONMENT_PATH="test-config/environments/${ENVIRONMENT_NAME}/netman-cf-acceptance.json"
export CONFIG=${PWD}/${CONFIG:-"${ENVIRONMENT_PATH}"}

echo $CONFIG

export NETWORK_STATS_FILE=$PWD/network-stats/stats.json

cd netman-release
export GOPATH=$PWD

go build -o /tmp/bin/network-policy-plugin ./src/cli-plugin
cf install-plugin -f /tmp/bin/network-policy-plugin

cd src/netman-cf-acceptance
export APPS_DIR=../example-apps
ginkgo -r -v
