#!/bin/bash

set -e

environment_path="${PWD}/test-config/environments/${ENVIRONMENT_NAME}"
export CONFIG=${CONFIG:-"$environment_path/netman-cf-acceptance.json"}

echo $CONFIG

export NETWORK_STATS_FILE=$PWD/network-stats/stats.json

cd netman-release
export GOPATH=$PWD

go build -o /tmp/bin/network-policy-plugin ./src/cli-plugin
cf install-plugin -f /tmp/bin/network-policy-plugin

cd src/netman-cf-acceptance
export APPS_DIR=../example-apps
ginkgo -r -v
