---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: container-networking-ci
  - name: deployments-repo
  - name: netman-release

outputs:
  - name: network-stats

params:
    ENVIRONMENT_NAME: ~

run:
  path: container-networking-ci/tasks/netman-cf-acceptance
