#!/bin/bash

set -e -u

export APPS_DIR=${PWD}/netman-release/src/example-apps

cd netman-release
export GOPATH=$PWD

environment_path="${PWD}/test-config/environments/${ENVIRONMENT_NAME}"
export CONFIG=$environment_path/netman-cf-acceptance.json
go run src/cf-pusher/cmd/cf-pusher/main.go --config "${CONFIG}"
