#!/bin/bash -eu

curl -L https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/download/v1.0.0/bbr-1.0.0.tar \
   --output /tmp/bbr.tar && tar -xvf /tmp/bbr.tar -C /tmp

export GOPATH=${PWD}/go
export PATH=$GOPATH/bin:$PATH

# install glide because drats doesn't
mkdir -p $GOPATH/bin
curl https://glide.sh/get | sh
curl -L -o /usr/local/bin/bosh-cli https://s3.amazonaws.com/bosh-cli-artifacts/bosh-cli-2.0.17-linux-amd64 && chmod +x /usr/local/bin/bosh-cli

# install policy plugin
cf install-plugin -f network-policy -r CF-Community

pushd deployments-repo/environments/$ENVIRONMENT_NAME > /dev/null
  export DEPLOYMENT_TO_BACKUP="cf"
  export DEPLOYMENT_TO_RESTORE="cf"
  export BOSH_URL=$(bbl director-address)
  export BOSH_CLIENT_SECRET=$(bbl director-password)
  export BOSH_CLIENT=$(bbl director-username)
  bbl director-ca-cert > /tmp/ca.crt
  export BOSH_CERT_PATH=/tmp/ca.crt
  export BBR_BUILD_PATH=/tmp/releases/bbr
popd

pushd $GOPATH/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests > /dev/null
  ./scripts/run_acceptance_tests.sh
popd
