---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

inputs:
  - name: cf-networking-ci
  - name: deployments-repo
  - name: disaster-recovery-acceptance-tests
    path: /go/src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests

params:
  ENVIRONMENT_NAME: ~

run:
  path: cf-networking-ci/tasks/run-drats
