---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/ducati-deploy }

inputs:
  - name: container-networking-ci

params:
  ENVIRONMENT_DIR: environment
  BOSH_USER: admin
  BOSH_PASSWORD: ~
  ERRAND: ~

run:
  path: container-networking-ci/tasks/run-errand

