---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

inputs:
  - name: container-networking-ci
  - name: environment

params:
  BOSH_USER: admin
  BOSH_PASSWORD: ~
  ERRAND: ~

run:
  path: container-networking-ci/tasks/run-errand
