platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

inputs:
  - name: container-networking-ci
  - name: scaling-deploy

run:
  path: container-networking-ci/tasks/set-scaling-deploy
