#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./netman-version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

CANDIDATE_DIR=$PWD/netman-release
cd netman-release

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

RELEASE_YML=$PWD/releases/netman/netman-${VERSION}.yml

if [ -e ${RELEASE_YML} ]; then
  echo "release already created; making tarball..."
  bosh -n create release --with-tarball ${RELEASE_YML}
else
  echo "finalizing release"
  bosh -n finalize release --version "$VERSION" ${CANDIDATE_DIR}/netman-*.tgz
  git add -A
  git commit -m "release v${VERSION}"
fi

mv releases/netman/*.tgz ../final-release/netman-${VERSION}.tgz
cp -r . ../release/master
