#!/bin/bash
# vim: set ft=sh

set -e -x

VERSION=$(cat ./version/number)
if [ -z "$VERSION" ]; then
  echo "missing version number"
  exit 1
fi

cp container-networking-deployments/config/private.yml netman-release/config/private.yml

CANDIDATE_DIR=$PWD/netman-tarball
cd netman-release

git config --global user.email "container-networking+ci@pivotal.io"
git config --global user.name "Container Networking Bot"

RELEASE_YML=$PWD/releases/netman/netman-${VERSION}.yml

if [ -e ${RELEASE_YML} ]; then
  echo "release already created; making tarball..."
  bosh -n create release --with-tarball ${RELEASE_YML}
else
  echo "finalizing release"
  bosh -n finalize release --version "$VERSION" ${CANDIDATE_DIR}/netman-*.tgz
  git add -A
  git commit -m "Release v${VERSION}"
fi

mv releases/netman/*.tgz ../final-release/netman-${VERSION}.tgz
cp -r . ../release/master
