#!/bin/bash

set -e -u

environment_path="${PWD}/test-config/environments/${ENVIRONMENT_NAME}"
pushd deployment-manifests
  export BASE_MANIFEST=$PWD/plain.yml
  export UPGRADE_MANIFEST=$PWD/with-netman.yml
popd

export CONFIG=$environment_path/netman-cf-acceptance.json
pushd "$environment_path"
	bbl director-ca-cert > /tmp/ca.crt
  export BOSH_DIRECTOR_URL=$(bbl director-address)
popd
export CA_CERT_CONFIG=/tmp/ca_cert_config.json
echo '
{
	"bosh_director_ca_cert": "/tmp/ca.crt",
  "bosh_director_url": "'"$BOSH_DIRECTOR_URL"'"
}
' > $CA_CERT_CONFIG

jq -s '.[0] * .[1]' "$CONFIG" "$CA_CERT_CONFIG" > /tmp/new-config.json
mv /tmp/new-config.json "$CONFIG"

cd netman-release
export GOPATH=$PWD
export PATH=$PATH:$GOPATH/bin

# export ASG_TARGET_IP=$(bosh-cli vms 2>/dev/null |grep router |grep -v ha_proxy|awk '{print  $11 }')
export ASG_TARGET_IP="10.0.16.8"

echo "manifests:"
echo "  base: ${BASE_MANIFEST}"
echo "  upgrade: ${UPGRADE_MANIFEST}"
echo "  ASG_TARGET_IP: ${ASG_TARGET_IP}"

go install ./src/github.com/onsi/ginkgo/ginkgo

cd src/netman-cf-upgrade
ginkgo -v
