---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-heavy }

platform: linux

params:
  ENVIRONMENT_NAME: ~
  BASE_MANIFEST: ~
  UPGRADE_MANIFEST: ~

inputs:
  - name: deployment-manifests
  - name: container-networking-ci
  - name: netman-release

run:
  path: container-networking-ci/tasks/test-upgrade
