#!/bin/bash

set -e -u

environment_path="${PWD}/test-config/environments/${ENVIRONMENT_NAME}"
export CONFIG=$environment_path/netman-cf-acceptance.json
export BASE_MANIFEST=${PWD}/${BASE_MANIFEST}
export UPGRADE_MANIFEST=${PWD}/${UPGRADE_MANIFEST}

cd netman-release
export GOPATH=$PWD
export PATH=$PATH:$GOPATH/bin

echo "manifests:"
echo "  base: ${BASE_MANIFEST}"
echo "  upgrade: ${UPGRADE_MANIFEST}"

go install ./src/github.com/onsi/ginkgo/ginkgo

cd src/netman-cf-upgrade
ginkgo -v
