---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

platform: linux

params:
  ENVIRONMENT_NAME: ~

inputs:
  - name: deployment-manifests
  - name: container-networking-ci
  - name: netman-release
  - name: test-config

run:
  path: container-networking-ci/tasks/test-upgrade
