---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

platform: linux

params:
  ENVIRONMENT_NAME: ~

inputs:
  - name: deployment-manifests

run:
  path: bash
  args:
    - -c
    - |
      echo "would do upgrade tests here.  for now, we found manifests: " \
        && ls -la deployment-manifests
