---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/small-git }

inputs:
  - name: cf-networking-ci
  - name: cf-deployment-patch
  - name: cf-deployment

params: {}

run:
  path: cf-networking-ci/tasks/update-cf-deployment-patch
