---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

platform: linux

inputs:
  - name: container-networking-ci
  - name: deployments-repo

run:
  path: container-networking-ci/tasks/update-runtime-config

params:
  ENVIRONMENT_NAME: ~
