#!/bin/bash

set -e -u

mkdir -p tmp
export BOSH_CA_CERT=$PWD/tmp/ca.cert

pushd deployments-repo/environments/$ENVIRONMENT_NAME
  export BOSH_ENVIRONMENT=$(bbl director-address)
  export BOSH_PASSWORD=$(bbl director-password)
  export BOSH_USER=$(bbl director-username)
  bbl director-ca-cert > ${BOSH_CA_CERT}
  export RUNTIME_VARS_FILE=$PWD/runtime-vars.yml
popd

bosh-cli -n update-runtime-config -l ${RUNTIME_VARS_FILE} container-networking-ci/runtime-config.yml
