#!/bin/bash
set -xeu

CF_DEPLOYMENT_PATCH_PATH="${PWD}/cf-deployment-patch"
pushd cf-deployment
  git remote add fork "$CF_DEPLOYMENT_PATCH_PATH"
  git fetch fork
  git config --global user.email "container-networking+ci@pivotal.io"
  git config --global user.name "Container Networking Bot"
  git merge --no-edit fork/release-candidate-patch
popd
