---
image_resource:
  type: docker-image
  source: {repository: c2cnetworking/deploy-light}

platform: linux

inputs:
  - name: bbl-state
  - name: cf-networking-ci
  - name: runtime-config
  - name: vars-store

run:
  path: cf-networking-ci/tasks/update-runtime-config

params:
  RUNTIME_CONFIG_FILE: ~
  VARS_STORE_FILE: ~
  BBL_STATE_DIR: ~
