resources:
  ###### Deployments
  - name: bosh-lite-environment
    type: bosh-deployment
    source:
      target: {{bosh-lite-private-ip}}
      username: admin
      password: {{bosh-lite-password}}
      deployment: ducati-guardian
  - name: uberzug
    type: bosh-deployment
    source:
      target: {{uberzug-bosh-host}}
      username: admin
      password: {{uberzug-password}}
      deployment: ducati-guardian
  - name: pickelhelm-cf
    type: bosh-deployment
    source:
      target: {{pickelhelm-bosh-host}}
      username: admin
      password: {{pickelhelm-bosh-password}}
      deployment: cf-diego
  - name: pickelhelm-diego
    type: bosh-deployment
    source:
      target: {{pickelhelm-bosh-host}}
      username: admin
      password: {{pickelhelm-bosh-password}}
      deployment: cf-diego-diego
  ###### Control plane
  - name: container-networking-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/container-networking-ci
  - name: pickelhelm-config
    type: git
    source:
      uri: "git@github.com:cloudfoundry/container-networking-deployments.git"
      branch: master
      private_key: {{container-networking-deployments-deploy-key}}
      paths: environments/pickelhelm
  - name: uberzug-config
    type: git
    source:
      uri: "git@github.com:cloudfoundry/container-networking-deployments.git"
      branch: master
      private_key: {{container-networking-deployments-deploy-key}}
      paths: environments/uberzug
  ###### Tools
  - name: ducatify
    type: git
    source:
      branch: master
      uri: git://github.com/cloudfoundry-incubator/ducatify.git
  ###### BOSH stemcells
  - name: aws-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  - name: boshlite-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  ###### BOSH releases
  - name: cf-release
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/cf-release.git
  - name: cf-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry/cf-release
  - name: consul-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/consul-release
  - name: diego-release
    type: git
    source:
      branch: ducati-dev
      ignore_paths:
        - dev_releases
        - git-hooks
        - releases
        - .final_builds
      uri: https://github.com/sykesm/diego-release.git
  - name: ducati-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/ducati-release
      branch: master
  - name: garden-runc-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/garden-runc-release
      branch: master
  - name: etcd-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/etcd-release
      branch: master

jobs:
  - name: ducati-tests
    public: true
    plan:
      - get: ducati-release
        trigger: true
      - task: ducati-tests
        file: ducati-release/ci/ducati-tests.yml
        privileged: true

  - name: garden-runc-tests
    public: true
    plan:
      - get: guardian-release
        trigger: true
        resource: garden-runc-release
      - task: garden-runc-tests
        file: guardian-release/ci/guardian.yml
        privileged: true

  - name: boshlite-deploy
    public: true
    serial_groups: [bosh-lite]
    plan:
      - aggregate:
        - get: boshlite-stemcell
          trigger: true
        - get: ducati-release
          trigger: true
          passed: [ducati-tests]
        - get: guardian-release
          resource: garden-runc-release
          trigger: true
          passed: [garden-runc-tests]
        - get: consul-release-tarball
        - get: container-networking-ci
      - task: create-release-tarballs
        file: container-networking-ci/tasks/create-release-tarballs.yml
        params:
          guardian_release_name: guardian
      - task: prep-manifest
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deploy }
          platform: linux
          inputs:
          - name: ducati-release
          outputs:
          - name: manifest
          run:
            path: bash
            args:
            - -c
            - |
              cat ducati-release/manifests/ducati-manifest.yml | grep -v director_uuid > manifest/manifest.yml
      - put: bosh-lite-environment
        params:
          cleanup: true
          manifest: manifest/manifest.yml
          stemcells:
          - boshlite-stemcell/*.tgz
          releases:
          - tarballs/*.tgz
          - consul-release-tarball/*.tgz

  - name: uberzug-deploy
    public: true
    serial: true
    serial_groups: [uberzug]
    plan:
      - aggregate:
        - get: container-networking-ci
          trigger: false
        - get: uberzug-config
          trigger: true
        - get: aws-stemcell
          trigger: true
        - get: consul-release-tarball
        - get: guardian-release
          resource: garden-runc-release
          trigger: true
          passed: [ garden-runc-tests ]
          params:
            submodules: all
        - get: ducati-release
          params:
            submodules: all
          trigger: true
          passed: [ ducati-tests ]
      - task: create-release-tarballs
        file: container-networking-ci/tasks/create-release-tarballs.yml
      - put: uberzug
        params:
          cleanup: true
          manifest: uberzug-config/environments/uberzug/uberzug.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - tarballs/*.tgz
          - consul-release-tarball/*.tgz

  - name: uberzug-test
    public: true
    serial_groups: [uberzug]
    plan:
      - aggregate:
        - get: ducati-release
          passed: [uberzug-deploy]
          params:
            submodules: none
        - get: guardian-release
          resource: garden-runc-release
          passed: [uberzug-deploy]
          params:
            submodules: all
        - get: container-networking-ci
          trigger: false
        - get: environment
          resource: uberzug
          passed: [uberzug-deploy]
          trigger: true
      - task: ducati-acceptance-tests
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{uberzug-password}}
          ERRAND: acceptance-tests
      - task: garden-integration-tests
        file: guardian-release/ci/non-nested-gits.yml
        params:
          GARDEN_ADDRESS: 10.0.1.12:7777

  - name: boshlite-test
    public: true
    serial_groups: [bosh-lite]
    plan:
      - aggregate:
        - get: ducati-release
          passed: [boshlite-deploy]
          params:
            submodules: none
        - get: garden-runc-release
          passed: [boshlite-deploy]
          params:
            submodules: none
        - get: container-networking-ci
          trigger: false
        - get: environment
          resource: bosh-lite-environment
          passed: [boshlite-deploy]
          trigger: true
      - task: ducati-acceptance-tests
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{bosh-lite-password}}
          ERRAND: acceptance-tests

  - name: pickelhelm-deploy
    serial_groups: [pickelhelm]
    plan:
      - aggregate:
        - get: container-networking-ci
          trigger: false
        - get: deployments-repo
          resource: pickelhelm-config
          trigger: false
        - get: cf-release
          trigger: false
          params:
            submodules: [src/loggregator] # needed for cf-lamb template
        - get: diego-release
          trigger: true
          params:
            submodules: all
        - get: aws-stemcell
          trigger: true
        - get: cf-release-tarball
          trigger: true
        - get: ducatify
        - get: garden-runc-release
          resource: garden-runc-release
          trigger: true
          passed: [boshlite-test, uberzug-test]
        - get: ducati-release
          trigger: true
          passed: [boshlite-test]
        - get: etcd-release
      - task: build-ducatify
        file: container-networking-ci/tasks/build-ducatify.yml
      - task: generate-pickelhelm-manifests
        file: container-networking-ci/tasks/generate-deployment-manifests.yml
        params:
          ENVIRONMENT_NAME: pickelhelm
      - task: create-release-tarballs
        file: container-networking-ci/tasks/create-release-tarballs.yml
      - task: create-diego-etcd-release-tarballs
        file: container-networking-ci/tasks/create-diego-etcd-release-tarballs.yml
      - put: pickelhelm-cf
        params:
          cleanup: true
          manifest: generated-manifest/cf.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - cf-release-tarball/*.tgz
      - put: pickelhelm-diego
        params:
          cleanup: true
          manifest: generated-manifest/diego_with_ducati.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - tarballs/*.tgz
          - diego-etcd-tarballs/*.tgz

  - name: pickelhelm-acceptance-tests
    serial_groups: [pickelhelm]
    plan:
      - get: container-networking-ci
      - get: environment
        resource: pickelhelm-diego
        passed: [pickelhelm-deploy]
        trigger: true
      - task: ducati-cf-acceptance
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          ERRAND: ducati-acceptance
      - get: environment
        resource: pickelhelm-cf
        passed: [pickelhelm-deploy]
        trigger: true
      - task: cats
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          ERRAND: acceptance_tests

##### Human-triggered utilities
  - name: delete-deployment-bosh-lite
    public: true
    serial_groups: [bosh-lite]
    plan:
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{bosh-lite-private-ip}}
          BOSH_USER: admin
          BOSH_PASSWORD: {{bosh-lite-password}}
          DEPLOYMENT_NAME: ducati-guardian
  - name: delete-deployment-uberzug
    public: true
    serial_groups: [uberzug]
    plan:
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{uberzug-bosh-host}}
          BOSH_USER: admin
          BOSH_PASSWORD: {{uberzug-password}}
          DEPLOYMENT_NAME: ducati-guardian
  - name: delete-deployment-pickelhelm-diego
    public: true
    serial_groups: [pickelhelm]
    plan:
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{pickelhelm-bosh-host}}
          BOSH_USER: admin
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          DEPLOYMENT_NAME: cf-diego-diego
  - name: delete-deployment-pickelhelm-cf
    public: true
    serial_groups: [pickelhelm]
    plan:
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{pickelhelm-bosh-host}}
          BOSH_USER: admin
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          DEPLOYMENT_NAME: cf-diego
