resources:
  ###### Deployments
  - name: boshlite
    type: bosh-deployment
    source:
      target: {{bosh-lite-private-ip}}
      username: admin
      password: {{bosh-lite-password}}
      deployment: ducati
  - name: uberzug
    type: bosh-deployment
    source:
      target: {{uberzug-bosh-host}}
      username: admin
      password: {{uberzug-password}}
      deployment: ducati
  - name: pickelhelm-cf
    type: bosh-deployment
    source:
      target: {{pickelhelm-bosh-host}}
      username: admin
      password: {{pickelhelm-bosh-password}}
      deployment: cf-diego
  - name: pickelhelm-diego
    type: bosh-deployment
    source:
      target: {{pickelhelm-bosh-host}}
      username: admin
      password: {{pickelhelm-bosh-password}}
      deployment: cf-diego-diego
  ###### Control plane
  - name: container-networking-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/container-networking-ci
  - name: pickelhelm-config
    type: git
    source:
      uri: "git@github.com:cloudfoundry/container-networking-deployments.git"
      branch: master
      private_key: {{container-networking-deployments-deploy-key}}
      paths: [ environments/pickelhelm ]
  - name: uberzug-config
    type: git
    source:
      uri: "git@github.com:cloudfoundry/container-networking-deployments.git"
      branch: master
      private_key: {{container-networking-deployments-deploy-key}}
      paths: [ environments/uberzug ]
  ###### BOSH stemcells
  - name: aws-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  - name: boshlite-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  ###### BOSH release repos
  - name: cf-release
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/cf-release.git
  - name: diego-release
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry-incubator/diego-release.git
  - name: ducati-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/ducati-release
      branch: master
  - name: netman-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/netman-release
      branch: master
  - name: garden-runc-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/garden-runc-release
      branch: master
  ###### BOSH release tarballs
  - name: rootfs-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry/cflinuxfs2-rootfs-release
  - name: consul-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/consul-release
  - name: etcd-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/etcd-release
  - name: diego-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/diego-release
  - name: cf-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry/cf-release
  - name: garden-runc-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/garden-runc-release

jobs:
  - name: ducati-tests
    public: true
    plan:
      - get: ducati-release
        trigger: true
      - task: ducati-tests
        file: ducati-release/ci/ducati-tests.yml
        privileged: true
  - name: netman-tests
    public: true
    plan:
      - get: netman-release
        trigger: true
      - task: netman-tests
        file: netman-release/ci/netman-tests.yml
        privileged: true

  - name: boshlite-deploy
    public: true
    serial_groups: [boshlite]
    plan:
      - aggregate:
        - get: boshlite-stemcell
          trigger: true
        # - get: ducati-release
        #   trigger: true
        #   passed: [ducati-tests]
        - get: netman-release
          trigger: true
          passed: [netman-tests]
        # - get: garden-runc-release
        #   resource: garden-runc-release
        #   trigger: true
        - get: garden-runc-release-tarball
          trigger: true
        - get: consul-release-tarball
        - get: container-networking-ci
      # - task: create-release-tarballs
      #   file: container-networking-ci/tasks/create-release-tarballs.yml
      #   params:
      #     guardian_release_name: garden-runc
      - task: create-release-tarball
        file: netman-release/ci/create-release-tarball.yml
      - task: prep-manifest
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deploy }
          platform: linux
          inputs:
          - name: ducati-release
          outputs:
          - name: manifest
          run:
            path: bash
            args:
            - -c
            - |
              cat ducati-release/manifests/ducati-manifest.yml | grep -v director_uuid > manifest/manifest.yml
      - put: boshlite
        params:
          cleanup: true
          manifest: manifest/manifest.yml
          stemcells:
          - boshlite-stemcell/*.tgz
          releases:
          - tarballs/*.tgz
          - consul-release-tarball/*.tgz

  - name: uberzug-deploy
    public: true
    serial: true
    serial_groups: [uberzug]
    plan:
      - aggregate:
        - get: container-networking-ci
          trigger: false
        - get: uberzug-config
          trigger: true
        - get: aws-stemcell
          trigger: true
        # - get: garden-runc-release
        #   resource: garden-runc-release
        #   trigger: true
        #   params: { submodules: all }
        - get: garden-runc-release-tarball
          trigger: true
        # - get: ducati-release
        #   params: { submodules: all }
        #   trigger: true
        #   passed: [ ducati-tests ]
        - get: netman-release
          params: { submodules: all }
          trigger: true
          passed: [ netman-tests ]
      # - task: create-release-tarballs
      #   file: container-networking-ci/tasks/create-release-tarballs.yml
      - task: create-release-tarball
        file: netman-release/ci/create-release-tarball.yml
      - put: uberzug
        params:
          cleanup: true
          manifest: uberzug-config/environments/uberzug/uberzug.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - tarballs/*.tgz

  - name: uberzug-test
    public: true
    serial_groups: [uberzug]
    plan:
      - aggregate:
        # - get: ducati-release
        #   passed: [uberzug-deploy]
        #   params: { submodules: none }
        - get: netman-release
          passed: [uberzug-deploy]
          params: { submodules: none }
        # - get: garden-runc-release
        #   resource: garden-runc-release
        #   passed: [uberzug-deploy]
        #   params: { submodules: all }
        - get: garden-runc-release-tarball
          passed: [uberzug-deploy]
        - get: container-networking-ci
          trigger: false
        - get: environment
          resource: uberzug
          passed: [uberzug-deploy]
          trigger: true
      # - task: ducati-acceptance-tests
      #   file: container-networking-ci/tasks/run-errand.yml
      #   params:
      #     BOSH_PASSWORD: {{uberzug-password}}
      #     ERRAND: acceptance-tests
      - task: netman-acceptance-tests
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{uberzug-password}}
          ERRAND: acceptance-tests
      - task: garden-integration-tests
        file: garden-runc-release/ci/non-nested-gits.yml
        input_mapping: {gr-release-develop: garden-runc-release}
        params:
          GARDEN_ADDRESS: 10.0.1.12:7777

  - name: boshlite-test
    public: true
    serial_groups: [boshlite]
    plan:
      - aggregate:
        # - get: ducati-release
        #   passed: [boshlite-deploy]
        #   params: { submodules: none }
        - get: netman-release
          passed: [boshlite-deploy]
          params: { submodules: none }
        # - get: garden-runc-release
        #   passed: [boshlite-deploy]
        #   params: { submodules: none }
        - get: garden-runc-release-tarball
          passed: [boshlite-deploy]
        - get: container-networking-ci
          trigger: false
        - get: environment
          resource: boshlite
          passed: [boshlite-deploy]
          trigger: true
      # - task: ducati-acceptance-tests
      #   file: container-networking-ci/tasks/run-errand.yml
      #   params:
      #     BOSH_PASSWORD: {{bosh-lite-password}}
      #     ERRAND: acceptance-tests
      - task: netman-acceptance-tests
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{uberzug-password}}
          ERRAND: acceptance-tests

  - name: pickelhelm-deploy
    serial_groups: [pickelhelm]
    plan:
      - aggregate:
        - get: container-networking-ci
          trigger: false
        - get: deployments-repo
          resource: pickelhelm-config
          trigger: false
        - get: cf-release
          params: { submodules: none }
        - get: diego-release
          params: { submodules: none }
        - get: aws-stemcell
          trigger: true
        - get: rootfs-release-tarball
        - get: cf-release-tarball
          trigger: true
        - get: diego-release-tarball
          trigger: true
        # - get: garden-runc-release
        #   resource: garden-runc-release
        #   trigger: true
        #   passed: [boshlite-test, uberzug-test]
        - get: garden-runc-release-tarball
          trigger: true
          passed: [boshlite-test, uberzug-test]
        # - get: ducati-release
        #   trigger: true
        #   passed: [boshlite-test, uberzug-test]
        - get: netman-release
          trigger: true
          passed: [boshlite-test, uberzug-test]
        - get: etcd-release-tarball
      - aggregate:
        # - task: create-release-tarballs
        #   file: container-networking-ci/tasks/create-release-tarballs.yml
        - task: create-release-tarball
          file: netman-release/ci/create-release-tarball.yml
      - task: generate-pickelhelm-manifests
        file: container-networking-ci/tasks/generate-deployment-manifests.yml
        params:
          ENVIRONMENT_NAME: pickelhelm
      - put: pickelhelm-cf
        params:
          cleanup: true
          manifest: generated-manifest/cf.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - cf-release-tarball/*.tgz
      - put: pickelhelm-diego
        params:
          cleanup: true
          manifest: generated-manifest/diego.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - tarballs/*.tgz
          - etcd-release-tarball/*.tgz
          - rootfs-release-tarball/*.tgz
          - diego-release-tarball/*.tgz

  - name: pickelhelm-test
    serial_groups: [pickelhelm]
    plan:
      - aggregate:
        - get: diego-release
          params: { submodules: none }
          passed: [pickelhelm-deploy]
          trigger: true
        - get: cf-release
          params: { submodules: none }
          passed: [pickelhelm-deploy]
          trigger: true
        # - get: garden-runc-release
        #   resource: garden-runc-release
        #   passed: [pickelhelm-deploy]
        #   trigger: true
        - get: garden-runc-release-tarball
          passed: [pickelhelm-deploy]
          trigger: true
        # - get: ducati-release
        #   passed: [pickelhelm-deploy]
        #   trigger: true
        - get: netman-release
          passed: [pickelhelm-deploy]
          trigger: true
      - get: container-networking-ci
      - get: environment
        resource: pickelhelm-diego
        passed: [pickelhelm-deploy]
        trigger: true
      # - task: ducati-cf-acceptance
      #   file: container-networking-ci/tasks/run-errand.yml
      #   params:
      #     BOSH_PASSWORD: {{pickelhelm-bosh-password}}
      #     ERRAND: ducati-acceptance
      - task: netman-cf-acceptance
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          ERRAND: netman-acceptance
      - get: environment
        resource: pickelhelm-cf
        passed: [pickelhelm-deploy]
        trigger: true
      - task: cats
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          ERRAND: acceptance_tests

##### Human-triggered utilities
  - name: delete-deployment-boshlite
    public: true
    serial_groups: [boshlite]
    plan:
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{bosh-lite-private-ip}}
          BOSH_USER: admin
          BOSH_PASSWORD: {{bosh-lite-password}}
          DEPLOYMENT_NAME: ducati
  - name: delete-deployment-uberzug
    public: true
    serial_groups: [uberzug]
    plan:
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{uberzug-bosh-host}}
          BOSH_USER: admin
          BOSH_PASSWORD: {{uberzug-password}}
          DEPLOYMENT_NAME: ducati
  - name: delete-deployment-pickelhelm-diego
    public: true
    serial_groups: [pickelhelm]
    plan:
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{pickelhelm-bosh-host}}
          BOSH_USER: admin
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          DEPLOYMENT_NAME: cf-diego-diego
  - name: delete-deployment-pickelhelm-cf
    public: true
    serial_groups: [pickelhelm]
    plan:
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{pickelhelm-bosh-host}}
          BOSH_USER: admin
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          DEPLOYMENT_NAME: cf-diego
