resources:
  ###### Deployments
  - name: bosh-lite-environment
    type: bosh-deployment
    source:
      target: {{bosh-lite-private-ip}}
      username: admin
      password: {{bosh-lite-password}}
      deployment: ducati-guardian
  - name: bosh-lite-environment-dev
    type: bosh-deployment
    source:
      target: {{bosh-lite-private-ip}}
      username: admin
      password: {{bosh-lite-password}}
      deployment: ducati-guardian-dev
  - name: pickelhelm-cf
    type: bosh-deployment
    source:
      target: {{pickelhelm-bosh-host}}
      username: admin
      password: {{pickelhelm-bosh-password}}
      deployment: cf-diego
  - name: pickelhelm-diego
    type: bosh-deployment
    source:
      target: {{pickelhelm-bosh-host}}
      username: admin
      password: {{pickelhelm-bosh-password}}
      deployment: cf-diego-diego
  ###### Control plane
  - name: container-networking-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/container-networking-ci
  - name: pickelhelm-config
    type: git
    source:
      uri: "git@github.com:cloudfoundry/container-networking-deployments.git"
      branch: master
      private_key: {{container-networking-deployments-deploy-key}}
      paths: environments/pickelhelm
  ###### BOSH stemcells
  - name: aws-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  - name: boshlite-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  ###### BOSH releases
  - name: cf-release
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/cf-release.git
  - name: cf-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry/cf-release
  - name: diego-release
    type: git
    source:
      branch: master
      ignore_paths:
        - dev_releases
        - git-hooks
        - releases
        - .final_builds
      uri: https://github.com/cloudfoundry-incubator/diego-release.git
  - name: diego-release-tarball
    type: github-release
    source:
      user: cloudfoundry-incubator
      repository: diego-release
  - name: ducati-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/ducati-release
      branch: master
  - name: guardian-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/guardian-release
      branch: master
  - name: guardian-release-dev
    type: git
    source:
      uri: git://github.com/dbellotti/guardian-release
      branch: gqt-dns-retries

jobs:
  - name: guardian-tests
    public: true
    plan:
      - get: guardian-release
        trigger: true
      - task: guardian-tests
        file: guardian-release/ci/guardian.yml
        privileged: true

  - name: ducati-tests
    public: true
    plan:
      - get: ducati-release
        trigger: true
      - task: ducati-tests
        file: ducati-release/ci/ducati-tests.yml
        privileged: true

  - name: guardian-tests-dev
    public: true
    plan:
      - get: guardian-release
        trigger: true
        resource: guardian-release-dev
      - task: guardian-tests-dev
        file: guardian-release/ci/guardian.yml
        privileged: true

  - name: deploy-to-bosh-lite
    public: true
    serial_groups: [bosh-lite]
    plan:
      - aggregate:
        - get: boshlite-stemcell
        - get: ducati-release
          trigger: true
          passed: [ducati-tests]
        - get: guardian-release
          trigger: true
          passed: [guardian-tests]
        - get: container-networking-ci
          params:
            submodules: none
      - task: create-release-tarballs
        file: container-networking-ci/tasks/create-release-tarballs.yml
      - task: prep-manifest
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deploy }
          platform: linux
          inputs:
          - name: ducati-release
          outputs:
          - name: manifest
          run:
            path: bash
            args:
            - -c
            - |
              cat ducati-release/manifests/ducati-manifest.yml | grep -v director_uuid > manifest/manifest.yml
      - put: bosh-lite-environment
        params:
          cleanup: true
          manifest: manifest/manifest.yml
          stemcells:
          - boshlite-stemcell/*.tgz
          releases:
          - tarballs/*.tgz

  - name: deploy-to-bosh-lite-dev
    public: true
    serial_groups: [bosh-lite-dev]
    plan:
      - aggregate:
        - get: boshlite-stemcell
        - get: ducati-release
          trigger: true
          passed: [ducati-tests]
        - get: guardian-release
          resource: guardian-release-dev
          trigger: true
          passed: [guardian-tests-dev]
        - get: container-networking-ci
          params:
            submodules: none
      - task: create-release-tarballs
        file: container-networking-ci/tasks/create-release-tarballs.yml
        params:
          guardian_release_name: guardian-dev
      - task: prep-manifest
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deploy }
          platform: linux
          inputs:
          - name: ducati-release
          outputs:
          - name: manifest
          run:
            path: bash
            args:
            - -c
            - |
              cat ducati-release/manifests/ducati-manifest-dev.yml | grep -v director_uuid > manifest/manifest.yml
      - put: bosh-lite-environment-dev
        params:
          cleanup: true
          manifest: manifest/manifest.yml
          stemcells:
          - boshlite-stemcell/*.tgz
          releases:
          - tarballs/*.tgz

  - name: remote-acceptance-tests
    public: true
    serial_groups: [bosh-lite]
    plan:
      - aggregate:
        - get: ducati-release
          passed: [deploy-to-bosh-lite]
          params:
            submodules: none
        - get: guardian-release
          passed: [deploy-to-bosh-lite]
          params:
            submodules: none
        - get: container-networking-ci
          trigger: false
          params:
            submodules: none
        - get: environment
          resource: bosh-lite-environment
          passed: [deploy-to-bosh-lite]
          trigger: true
      - task: remote-acceptance-tests
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{bosh-lite-password}}
          ERRAND: acceptance-tests

  - name: remote-acceptance-tests-dev
    public: true
    serial_groups: [bosh-lite-dev]
    plan:
      - aggregate:
        - get: ducati-release
          passed: [deploy-to-bosh-lite-dev]
          params:
            submodules: none
        - get: guardian-release-dev
          passed: [deploy-to-bosh-lite-dev]
          params:
            submodules: none
        - get: container-networking-ci
          trigger: false
          params:
            submodules: none
        - get: environment
          resource: bosh-lite-environment-dev
          passed: [deploy-to-bosh-lite-dev]
          trigger: true
      - task: remote-acceptance-tests
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{bosh-lite-password}}
          ERRAND: acceptance-tests

  - name: pickelhelm-diego-deploy
    serial_groups: [pickelhelm]
    plan:
      - aggregate:
        - get: container-networking-ci
          trigger: false
          params:
            submodules: none
        - get: deployments-repo
          resource: pickelhelm-config
          trigger: false
        - get: cf-release
          trigger: false
          params:
            submodules: [src/loggregator] # needed for cf-lamb template
        - get: diego-release
          trigger: false
          params:
            submodules: none
        - get: aws-stemcell
          trigger: true
        - get: cf-release-tarball
          trigger: true
        - get: diego-release-tarball
          trigger: true
        - get: guardian-release
          trigger: true
          passed: [remote-acceptance-tests]
      - task: generate-pickelhelm-manifests
        file: container-networking-ci/tasks/generate-deployment-manifests.yml
        params:
          ENVIRONMENT_NAME: pickelhelm
      - task: inject-guardian
        file: container-networking-ci/tasks/inject-guardian.yml
      - task: ducatify
        file: container-networking-ci/tasks/ducatify.yml
      - task: create-release-tarballs
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deploy }
          platform: linux
          inputs:
          - name: guardian-release
          outputs:
          - name: tarballs
          run:
            path: bash
            args:
            - -c
            - |
               bosh create release --version $(date "+%s") --with-tarball --name guardian --dir guardian-release \
               && cp guardian-release/dev_releases/guardian/*.tgz tarballs
      - put: pickelhelm-cf
        params:
          cleanup: true
          manifest: generated-manifest/cf.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - cf-release-tarball/*.tgz
      - put: pickelhelm-diego
        params:
          cleanup: true
          manifest: guardian-generated-manifest/diego.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - tarballs/*.tgz
          - diego-release-tarball/diego-*.tgz
          - diego-release-tarball/etcd-*.tgz

  - name: pickelhelm-acceptance-tests
    serial_groups: [pickelhelm]
    plan:
      - aggregate:
        - get: diego-release
          passed: [pickelhelm-diego-deploy]
          params:
            submodules: none
        - get: container-networking-ci
          params:
            submodules: none
        - get: environment
          resource: pickelhelm-cf
          passed: [pickelhelm-diego-deploy]
          trigger: true
        - get: pickelhelm-diego
          passed: [pickelhelm-diego-deploy]
          trigger: true
      - task: cats
        file: container-networking-ci/tasks/run-errand.yml
        params:
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          ERRAND: acceptance_tests

##### Human-triggered utilities
  - name: delete-deployment-bosh-lite
    public: true
    serial_groups: [bosh-lite]
    plan:
      - task: delete-deployment
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deploy }
          platform: linux
          run:
            path: bash
            args:
            - -c
            - |
              bosh target $BOSH_TARGET && \
              bosh -n delete deployment $DEPLOYMENT_NAME
          params:
            BOSH_TARGET: {{bosh-lite-private-ip}}
            DEPLOYMENT_NAME: ducati-guardian
            BOSH_USER: admin
            BOSH_PASSWORD: {{bosh-lite-password}}
  - name: delete-deployment-bosh-lite-dev
    public: true
    serial_groups: [bosh-lite-dev]
    plan:
      - task: delete-deployment
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deploy }
          platform: linux
          run:
            path: bash
            args:
            - -c
            - |
              bosh target $BOSH_TARGET && \
              bosh -n delete deployment $DEPLOYMENT_NAME
          params:
            BOSH_TARGET: {{bosh-lite-private-ip}}
            DEPLOYMENT_NAME: ducati-guardian-dev
            BOSH_USER: admin
            BOSH_PASSWORD: {{bosh-lite-password}}
