resources:
  ###### Deployments
  - name: bosh-lite-environment
    type: bosh-deployment
    source:
      target: {{bosh-lite-private-ip}}
      username: admin
      password: {{bosh-lite-password}}
      deployment: ducati-guardian
  - name: pickelhelm-cf
    type: bosh-deployment
    source:
      target: {{pickelhelm-bosh-host}}
      username: admin
      password: {{pickelhelm-bosh-password}}
      deployment: cf-diego
  - name: pickelhelm-diego
    type: bosh-deployment
    source:
      target: {{pickelhelm-bosh-host}}
      username: admin
      password: {{pickelhelm-bosh-password}}
      deployment: cf-diego-diego
  ###### Control plane
  - name: diego-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/diego-ci
  - name: container-networking-deployments
    type: git
    source:
      uri: "git@github.com:cloudfoundry/container-networking-deployments.git"
      branch: master
      private_key: {{container-networking-deployments-deploy-key}}
  ###### BOSH stemcells
  - name: aws-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  - name: boshlite-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
  ###### BOSH releases
  - name: cf-release
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/cf-release.git
  - name: cf-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry/cf-release
  - name: diego-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/diego-release
  - name: diego-release
    type: git
    source:
      branch: master
      ignore_paths:
        - dev_releases
        - git-hooks
        - releases
        - .final_builds
      uri: https://github.com/cloudfoundry-incubator/diego-release.git
  - name: ducati-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/ducati-release
      branch: master
  - name: etcd-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/etcd-release
  - name: garden-linux-release-tarball
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/garden-linux-release
  - name: guardian-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/guardian-release
      branch: master

jobs:
  - name: guardian-tests
    public: true
    plan:
      - get: guardian-release
        trigger: true
      - task: guardian-tests
        file: guardian-release/ci/guardian.yml
        privileged: true

  - name: ducati-tests
    public: true
    plan:
      - get: ducati-release
        trigger: true
      - task: ducati-tests
        file: ducati-release/ci/ducati-tests.yml
        privileged: true

  - name: deploy-to-bosh-lite
    public: true
    serial_groups: [bosh-lite]
    plan:
      - aggregate:
        - get: boshlite-stemcell
        - get: ducati-release
          trigger: true
          passed: [ducati-tests]
        - get: guardian-release
          trigger: true
          passed: [guardian-tests]
      - task: create-release-tarballs
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deployment }
          platform: linux
          inputs:
          - name: ducati-release
          - name: guardian-release
          outputs:
          - name: tarballs
          run:
            path: bash
            args:
            - -c
            - |
              bosh create release --version $(date "+%s") --with-tarball --name ducati --dir ducati-release \
               && bosh create release --version $(date "+%s") --with-tarball --name guardian --dir guardian-release \
               && cp ducati-release/dev_releases/ducati/*.tgz tarballs \
               && cp guardian-release/dev_releases/guardian/*.tgz tarballs
      - task: prep-manifest
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deployment }
          platform: linux
          inputs:
          - name: ducati-release
          outputs:
          - name: manifest
          run:
            path: bash
            args:
            - -c
            - |
              cat ducati-release/manifests/ducati-manifest.yml | grep -v director_uuid > manifest/manifest.yml
      - put: bosh-lite-environment
        params:
          cleanup: true
          manifest: manifest/manifest.yml
          stemcells:
          - boshlite-stemcell/*.tgz
          releases:
          - tarballs/*.tgz

  - name: remote-acceptance-tests
    public: true
    serial_groups: [bosh-lite]
    plan:
      - get: ducati-release
        trigger: true
        passed: [deploy-to-bosh-lite]
      - get: guardian-release
        trigger: true
        passed: [deploy-to-bosh-lite]
      - task: remote-acceptance-tests
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deployment }
          platform: linux
          run:
            path: bash
            args:
            - -c
            - |
              bosh target $BOSH_TARGET && \
              bosh download manifest $DEPLOYMENT_NAME manifest.yml && \
              bosh deployment manifest.yml && \
              bosh run errand $ERRAND
          params:
            BOSH_TARGET: {{bosh-lite-private-ip}}
            DEPLOYMENT_NAME: ducati-guardian
            BOSH_USER: admin
            BOSH_PASSWORD: {{bosh-lite-password}}
            ERRAND: acceptance-tests

  - name: pickelhelm-diego-deploy
    plan:
      - aggregate:
        - get: container-networking-deployments
          trigger: false
        - get: aws-stemcell
          trigger: false
        - get: cf-release-tarball
          trigger: false
        - get: diego-release-tarball
          trigger: false
        - get: etcd-release-tarball
          trigger: false
        - get: garden-linux-release-tarball
          trigger: false
      - put: pickelhelm-cf
        params:
          cleanup: true
          manifest: container-networking-deployments/environments/pickelhelm/deployments/cf.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - cf-release-tarball/*.tgz
      - put: pickelhelm-diego
        params:
          cleanup: true
          manifest: container-networking-deployments/environments/pickelhelm/deployments/diego.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - garden-linux-release-tarball/*.tgz
          - etcd-release-tarball/*.tgz
          - diego-release-tarball/*.tgz

##### Human-triggered utilities
  - name: delete-deployment-bosh-lite
    public: true
    serial_groups: [bosh-lite]
    plan:
      - task: delete-deployment
        config:
          image_resource:
            type: docker-image
            source: { repository: c2cnetworking/ducati-deployment }
          platform: linux
          run:
            path: bash
            args:
            - -c
            - |
              bosh target $BOSH_TARGET && \
              bosh download manifest $DEPLOYMENT_NAME manifest.yml && \
              bosh deployment manifest.yml && \
              bosh -n delete deployment $DEPLOYMENT_NAME
          params:
            BOSH_TARGET: {{bosh-lite-private-ip}}
            DEPLOYMENT_NAME: ducati-guardian
            BOSH_USER: admin
            BOSH_PASSWORD: {{bosh-lite-password}}
