resources:
  - name: guardian-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/guardian-release
      branch: master
  - name: ducati-release
    type: git
    source:
      uri: git://github.com/cloudfoundry-incubator/ducati-release
      branch: master

jobs:
  - name: guardian-tests-unit
    plan:
      - get: guardian-release
        trigger: true
      - task: guardian-tests-unit
        file: guardian-release/ci/nested-guardian-tests.yml
        privileged: true

  - name: ducati-tests
    plan:
      - get: ducati-release
        trigger: true
      - task: ducati-tests
        file: ducati-release/ci/ducati-tests.yml
        privileged: true
