resources:
- name: ducati-dev-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/ducati-release
    branch: master
    paths:
      - Dockerfile

- name: dockerhub
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/ducati-dev

jobs:
- name: build-ducati-dev-image
  plan:
  - get: ducati-dev-dockerfile
    params: {submodules: all}
    trigger: true
  - put: dockerhub
    params: {build: ducati-dev-dockerfile}
