resources:
- name: dev-postgres-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/dev-postgres

- name: dev-postgres-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/dev-postgres

- name: dev-mysql-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/dev-mysql

- name: dev-mysql-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/dev-mysql

- name: deploy-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/deploy

- name: deploy-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/deploy

- name: aws-ops-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/aws-ops

- name: aws-ops-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/aws-ops

- name: small-git-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/small-git

- name: small-git-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/small-git

- name: deploy-light-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/deploy-light

- name: deploy-light-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/deploy-light

- name: golang-1.x-tarball
  type: s3
  source:
    endpoint: storage.googleapis.com
    bucket: golang
    regexp: 'go(1\.\d+(\.\d+)?)\.linux-amd64\.tar.gz'

- name: container-networking-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/container-networking-ci

jobs:
- name: build-dev-postgres-image
  plan:
  - aggregate:
    - get: container-networking-ci
    - get: dev-postgres-dockerfile
      trigger: true
    - get: golang-1.x-tarball
      trigger: true
  - task: add-golang
    file: container-networking-ci/tasks/add-golang-to-docker-context.yml
    input_mapping:
      dockerfile: dev-postgres-dockerfile
    params:
      INPUT_DOCKERFILE_PATH: dockerfile/dockerfiles/dev-postgres/Dockerfile
  - put: dev-postgres-image
    params:
      build: docker-build-context

- name: build-dev-mysql-image
  plan:
  - get: dev-mysql-dockerfile
    trigger: true
  - put: dev-mysql-image
    params:
      build: dev-mysql-dockerfile/dockerfiles/dev-mysql

- name: build-deploy-image
  plan:
  - get: deploy-dockerfile
    trigger: true
  - put: deploy-image
    params:
      build: deploy-dockerfile/dockerfiles/deploy

- name: build-aws-ops-image
  plan:
  - get: aws-ops-dockerfile
    trigger: true
  - put: aws-ops-image
    params:
      build: aws-ops-dockerfile/dockerfiles/aws-ops

- name: build-small-git-image
  plan:
  - get: small-git-dockerfile
    trigger: true
  - put: small-git-image
    params:
      build: small-git-dockerfile/dockerfiles/small-git

- name: build-deploy-light-image
  plan:
  - get: deploy-light-dockerfile
    trigger: true
  - put: deploy-light-image
    params:
      build: deploy-light-dockerfile/dockerfiles/deploy-light
