resources:
- name: dev-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/dev

- name: dev-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/dev

- name: deploy-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/deploy

- name: deploy-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/deploy

- name: aws-ops-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/aws-ops

- name: aws-ops-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/aws-ops

jobs:
- name: build-dev-image
  plan:
  - get: dev-dockerfile
    trigger: true
  - put: dev-image
    params:
      build: dev-dockerfile/dockerfiles/dev

- name: build-deploy-image
  plan:
  - get: deploy-dockerfile
    trigger: true
  - put: deploy-image
    params:
      build: deploy-dockerfile/dockerfiles/deploy

- name: build-aws-ops-image
  plan:
  - get: aws-ops-dockerfile
    trigger: true
  - put: aws-ops-image
    params:
      build: aws-ops-dockerfile/dockerfiles/aws-ops
