resources:
- name: dev-postgres-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/dev-postgres

- name: dev-postgres-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/dev-postgres

- name: dev-mysql-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/dev-mysql

- name: dev-mysql-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/dev-mysql

- name: deploy-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/deploy

- name: deploy-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/deploy

- name: aws-ops-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/aws-ops

- name: aws-ops-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/aws-ops

- name: small-git-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/small-git

- name: small-git-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/small-git

- name: deploy-light-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/deploy-light

- name: deploy-light-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/deploy-light

- name: deploy-heavy-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/deploy-heavy

- name: deploy-heavy-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/deploy-heavy

- name: run-cats-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - dockerfiles/run-cats

- name: run-cats-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/run-cats

jobs:
- name: build-dev-postgres-image
  plan:
  - get: dev-postgres-dockerfile
    trigger: true
  - put: dev-postgres-image
    params:
      build: dev-postgres-dockerfile/dockerfiles/dev-postgres

- name: build-dev-mysql-image
  plan:
  - get: dev-mysql-dockerfile
    trigger: true
  - put: dev-mysql-image
    params:
      build: dev-mysql-dockerfile/dockerfiles/dev-mysql

- name: build-deploy-image
  plan:
  - get: deploy-dockerfile
    trigger: true
  - put: deploy-image
    params:
      build: deploy-dockerfile/dockerfiles/deploy

- name: build-aws-ops-image
  plan:
  - get: aws-ops-dockerfile
    trigger: true
  - put: aws-ops-image
    params:
      build: aws-ops-dockerfile/dockerfiles/aws-ops

- name: build-small-git-image
  plan:
  - get: small-git-dockerfile
    trigger: true
  - put: small-git-image
    params:
      build: small-git-dockerfile/dockerfiles/small-git

- name: build-deploy-light-image
  plan:
  - get: deploy-light-dockerfile
    trigger: true
  - put: deploy-light-image
    params:
      build: deploy-light-dockerfile/dockerfiles/deploy-light

- name: build-deploy-heavy-image
  plan:
  - get: deploy-heavy-dockerfile
    trigger: true
  - put: deploy-heavy-image
    params:
      build: deploy-heavy-dockerfile/dockerfiles/deploy-heavy

- name: build-run-cats
  plan:
  - get: run-cats-dockerfile
    trigger: true
  - put: run-cats-image
    params:
      build: run-cats-dockerfile/dockerfiles/run-cats
