resources:
- name: ducati-dev-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - images/ducati-dev

- name: ducati-dev-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/ducati-dev

- name: ducati-deploy-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - images/ducati-deploy

- name: ducati-deploy-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/ducati-deployment

- name: aws-ops-dockerfile
  type: git
  source:
    uri: git://github.com/cloudfoundry-incubator/container-networking-ci
    branch: master
    paths:
      - images/aws-ops

- name: aws-ops-image
  type: docker-image
  source:
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}
    email: {{dockerhub_email}}
    repository: c2cnetworking/aws-ops

jobs:
- name: build-ducati-dev-image
  plan:
  - get: ducati-dev-dockerfile
    trigger: true
  - put: ducati-dev-image
    params:
      build: ducati-dev-dockerfile/images/ducati-dev

- name: build-ducati-deploy-image
  plan:
  - get: ducati-deploy-dockerfile
    trigger: true
  - put: ducati-deploy-image
    params:
      build: ducati-deploy-dockerfile/images/ducati-deploy

- name: build-aws-ops-image
  plan:
  - get: aws-ops-dockerfile
    trigger: true
  - put: aws-ops-image
    params:
      build: aws-ops-dockerfile/images/aws-ops
