groups:
- name: netman
  jobs:
  - mysql-tests
  - postgres-tests
  - pickelhelm-deploy
  - pickelhelm-test
  - mitre-deploy
  - mitre-test
  - mitre-netman-errand
  - mitre-cats
  - netman-shipit
  - netman-bump-minor-version
  - netman-merge-master
  - toque-deploy
  - toque-push
  - toque-test
- name: toque
  jobs:
  - toque-deploy
  - toque-push
  - toque-test
- name: cleanup
  jobs:
    - delete-deployment-mitre-cf
    - delete-deployment-pickelhelm-cf
    - delete-deployment-toque-cf
- name: version
  jobs:
  - major-bump
  - minor-bump
  - patch-bump

resources:
  ###### Deployments
  - name: pickelhelm-cf
    type: bosh-deployment
    source:
      target: {{pickelhelm-bosh-host}}
      username: {{pickelhelm-bosh-user}}
      password: {{pickelhelm-bosh-password}}
      deployment: cf
  - name: mitre-cf
    type: bosh-deployment
    source:
      target: {{mitre-bosh-host}}
      username: {{mitre-bosh-user}}
      password: {{mitre-bosh-password}}
      deployment: cf
  - name: toque-cf
    type: bosh-deployment
    source:
      target: {{toque-bosh-host}}
      username: {{toque-bosh-user}}
      password: {{toque-bosh-password}}
      deployment: cf
  ###### Control plane
  - name: container-networking-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/container-networking-ci
  # - name: toque-scaling-deploy
  #   type: git
  #   source:
  #     uri: https://github.com/cf-container-networking/toque-scaling
  #     paths: [ deploy ]
  - name: container-networking-deployments
    type: git
    source:
      uri: "git@github.com:cloudfoundry/container-networking-deployments.git"
      branch: master
      private_key: {{container-networking-deployments-push-key}}
  - name: cats-concourse-task
    type: git
    source:
      uri: https://github.com/cloudfoundry/cats-concourse-task
      branch: master
  ###### BOSH stemcells
  - name: aws-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  ###### BOSH release repos
  # - name: cf-release-master
  #   type: git
  #   source:
  #     branch: master
  #     uri: https://github.com/cloudfoundry/cf-release.git
  # - name: diego-release
  #   type: git
  #   source:
  #     branch: master
  #     uri: https://github.com/cloudfoundry/diego-release.git
  - name: cf-networking-dev
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/cf-networking.git
      branch: develop
      ignore_paths:
        - docs
      private_key: {{netman-release-deploy-key}}
  - name: cf-networking-master
    type: git
    source:
      uri: git@github.com:cloudfoundry-incubator/cf-networking.git
      branch: master
      private_key: {{netman-release-deploy-key}}
  ###### BOSH release tarballs
  # - name: rootfs-release-tarball
  #   type: bosh-io-release
  #   source:
  #     repository: cloudfoundry/cflinuxfs2-rootfs-release
  # - name: etcd-release-tarball
  #   type: bosh-io-release
  #   source:
  #     repository: cloudfoundry-incubator/etcd-release
  # - name: diego-release-tarball
  #   type: bosh-io-release
  #   source:
  #     repository: cloudfoundry/diego-release
  # - name: cf-release-tarball
  #   type: bosh-io-release
  #   source:
  #     repository: cloudfoundry/cf-release
  # - name: garden-runc-release-tarball
  #   type: bosh-io-release
  #   source:
  #     repository: cloudfoundry/garden-runc-release
  ####### Stats
  - name: mitre-stats
    type: git
    source:
      uri: "git@github.com:cf-container-networking/mitre-stats.git"
      branch: master
      private_key: {{container-networking-bot-key}}
  - name: toque-stats
    type: git
    source:
      uri: "git@github.com:cf-container-networking/toque-stats.git"
      branch: master
      private_key: {{container-networking-bot-key}}
  ####### Timers
  - name: every-half-hour
    type: time
    source:
      interval: 30m
  ####### Tests
  - name: cf-acceptance-tests
    type: git
    source:
      branch: master
      uri: git://github.com/cloudfoundry/cf-acceptance-tests.git
  - name: toque-scaling-test-params
    type: git
    source:
      uri: https://github.com/cf-container-networking/toque-scaling
      paths: [ test-params ]
  #######  Release management
  - name: version
    type: semver
    source:
      bucket: {{netman-release-s3-bucket}}
      region_name: us-west-2
      initial_version: 0.2.0-rc.1
      key: releases/current-version
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  - name: netman-tarball
    type: s3
    source:
      bucket: {{netman-candidate-s3-bucket}}
      region_name: us-west-2
      regexp: releases/netman-(.*).tgz
      access_key_id: {{aws-access-key-id}}
      secret_access_key: {{aws-secret-access-key}}
  # Github release
  - name: cf-networking-github-release
    type: github-release
    source:
      user: cloudfoundry-incubator
      repository: cf-networking
      access_token: {{github-access-token}}
      drafts: true
  - name: cf-deployment
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/cf-deployment.git

jobs:
  - name: postgres-tests
    public: true
    plan:
    - aggregate:
      - get: cf-networking
        resource: cf-networking-dev
        trigger: true
    - task: netman-tests
      file: cf-networking/ci/postgres-tests.yml
      privileged: true

  - name: mysql-tests
    public: true
    plan:
    - aggregate:
      - get: cf-networking
        resource: cf-networking-dev
        trigger: true
    - task: netman-tests
      file: cf-networking/ci/mysql-tests.yml
      privileged: true

  - name: pickelhelm-deploy
    serial_groups: [pickelhelm]
    plan:
      - aggregate:
        - get: container-networking-ci
          resource: container-networking-ci
        - get: deployments-repo
          resource: container-networking-deployments
        - get: aws-stemcell
          trigger: true
        - get: cf-deployment
          trigger: true
        - get: netman-release
          resource: cf-networking-dev
          trigger: true
          passed: [postgres-tests, mysql-tests]
      - aggregate:
        - task: create-release-tarball
          file: netman-release/ci/create-release-tarball.yml
        - task: generate-pickelhelm-manifest
          file: container-networking-ci/tasks/generate-cf-deployment-manifest.yml
          params:
            ENVIRONMENT_NAME: pickelhelm
      - put: pickelhelm-cf
        params:
          cleanup: false
          manifest: deployment-manifest/cf-with-netman.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - tarballs/*.tgz
      - put: container-networking-deployments
        params:
          repository: deployments-repo-output
          rebase: true

  - name: pickelhelm-test
    serial_groups: [pickelhelm]
    plan:
      - aggregate:
        - get: container-networking-ci
        - get: deployments-repo
          resource: container-networking-deployments
        - get: test-config
          resource: container-networking-deployments
        - get: netman-release
          resource: cf-networking-dev
          passed: [pickelhelm-deploy]
          trigger: true
        - get: cf-deployment
          passed: [pickelhelm-deploy]
          trigger: true
        - get: pickelhelm-cf
          passed: [pickelhelm-deploy]
          trigger: true
        - get: aws-stemcell
          passed: [pickelhelm-deploy]
      - task: netman-cf-acceptance
        file: container-networking-ci/tasks/netman-cf-acceptance.yml
        params:
          ENVIRONMENT_NAME: pickelhelm

  - name: mitre-deploy
    serial_groups: [mitre, version]
    plan:
      - aggregate:
        - get: container-networking-ci
          resource: container-networking-ci
        - get: deployments-repo
          resource: container-networking-deployments
        - get: cf-deployment
          passed: [pickelhelm-test]
          trigger: true
        - get: aws-stemcell
          passed: [pickelhelm-test]
          trigger: true
        - get: netman-release
          resource: cf-networking-dev
          passed: [pickelhelm-test]
          trigger: true
        - get: version
          params:
            pre: rc
      - aggregate:
        - task: create-release-tarball
          file: netman-release/ci/create-release-tarball.yml
        - task: generate-mitre-manifest
          file: container-networking-ci/tasks/generate-cf-deployment-manifest.yml
          params:
            ENVIRONMENT_NAME: mitre
      - put: netman-tarball
        params:
          from: tarballs/netman-([^/]*).tgz
          to: releases/
      - put: version
        params: {file: version/number}
      - put: mitre-cf
        params:
          cleanup: false
          manifest: deployment-manifest/cf-with-netman.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - tarballs/*.tgz
      - put: container-networking-deployments
        params:
          repository: deployments-repo-output
          rebase: true

  - name: mitre-test
    serial_groups: [mitre]
    plan:
      - aggregate:
        - get: deployments-repo
          resource: container-networking-deployments
        - get: test-config
          resource: container-networking-deployments
        - get: netman-release
          resource: cf-networking-dev
          passed: [mitre-deploy]
          trigger: true
        - get: netman-tarball
          passed: [mitre-deploy]
        - get: version
          passed: [mitre-deploy]
        - get: container-networking-ci
        - get: cf-deployment
          passed: [mitre-deploy]
          trigger: true
        - get: mitre-stats
        - get: mitre-cf
          passed: [mitre-deploy]
          trigger: true
      - task: netman-cf-acceptance
        file: container-networking-ci/tasks/netman-cf-acceptance.yml
        params:
          ENVIRONMENT_NAME: mitre
      - task: commit-stats
        file: container-networking-ci/tasks/commit-new-file.yml
        input_mapping:
          input_repo: mitre-stats
          source: network-stats
        output_mapping: {output_repo: stats_output}
        params:
          SOURCE_FILE: stats.json
          DEST_SUFFIX: json
      - put: mitre-stats
        params: {repository: stats_output}

  - name: mitre-netman-errand
    serial_groups: [mitre]
    plan:
      - aggregate:
        - get: container-networking-ci
        - get: netman-release
          resource: cf-networking-dev
          passed: [mitre-test]
          trigger: true
        - get: cf-deployment
          passed: [mitre-test]
          trigger: true
        - get: deployments-repo
          resource: container-networking-deployments
        - get: netman-tarball
          passed: [mitre-test]
        - get: version
          passed: [mitre-test]
      - task: run-errand
        file: container-networking-ci/tasks/run-errand.yml
        params:
          ENVIRONMENT_NAME: mitre
          ERRAND: netman-cf-acceptance

  - name: mitre-cats
    serial_groups: [mitre]
    plan:
      - aggregate:
        - get: container-networking-ci
        - get: cf-acceptance-tests
          resource: cf-acceptance-tests
        - get: cats-concourse-task
        - get: netman-release
          resource: cf-networking-dev
          passed: [mitre-test]
          trigger: true
        - get: cf-deployment
          passed: [mitre-test]
          trigger: true
        - get: container-networking-deployments
        - get: netman-tarball
          passed: [mitre-test]
        - get: version
          passed: [mitre-test]
      - task: copy-config
        params:
          ENVIRONMENT: mitre
        file: container-networking-ci/tasks/copy-config.yml
      - task: cats
        file: cats-concourse-task/task.yml
        params:
          NODES: 16

  - name: toque-deploy
    serial_groups: [toque]
    plan:
      - aggregate:
        - get: container-networking-ci
          resource: container-networking-ci
        - get: deployments-repo
          resource: container-networking-deployments
        - get: cf-deployment
          trigger: true
        - get: aws-stemcell
          trigger: true
        - get: netman-release
          resource: cf-networking-dev
          trigger: true
          passed: [postgres-tests, mysql-tests]
      - aggregate:
        - task: create-release-tarball
          file: netman-release/ci/create-release-tarball.yml
        - task: generate-toque-manifests
          file: container-networking-ci/tasks/generate-cf-deployment-manifest.yml
          params:
            ENVIRONMENT_NAME: toque
      - put: toque-cf
        params:
          cleanup: false
          manifest: deployment-manifest/cf-with-netman.yml
          stemcells:
          - aws-stemcell/*.tgz
          releases:
          - tarballs/*.tgz
      - put: container-networking-deployments
        params:
          repository: deployments-repo-output
          rebase: true

  - name: toque-push
    serial_groups: [toque]
    plan:
      - aggregate:
        - get: deployments-repo
          resource: container-networking-deployments
        - get: netman-release
          resource: cf-networking-dev
          passed: [toque-deploy]
          trigger: true
        - get: container-networking-ci
        - get: scaling-test-params
          resource: toque-scaling-test-params
          trigger: true
      - task: set-scaling-test-params
        file: container-networking-ci/tasks/set-scaling-test-params.yml
        params:
          ENVIRONMENT_NAME: toque
      - task: push-apps
        file: container-networking-ci/tasks/push-apps.yml
        params:
          ENVIRONMENT_NAME: toque

  - name: toque-test
    serial_groups: [toque]
    plan:
      - aggregate:
        - get: every-half-hour
          trigger: true
        - get: deployments-repo
          resource: container-networking-deployments
        - get: netman-release
          resource: cf-networking-dev
          passed: [toque-push]
        - get: container-networking-ci
        - get: cf-deployment
          resource: toque-cf
        - get: scaling-test-params
          resource: toque-scaling-test-params
          passed: [toque-push]
        - get: toque-stats
      - task: set-scaling-test-params
        file: container-networking-ci/tasks/set-scaling-test-params.yml
        params:
          ENVIRONMENT_NAME: toque
      - task: emit-datadog-test-start
        file: container-networking-ci/tasks/emit-datadog-event.yml
        params:
          TITLE: test_start
          TEXT: test_start
          PRIORITY: normal
          AWS_ENV: toque.c2c.cf-app.com
          DATADOG_API_KEY: {{datadog_api_key}}
      - task: test-scalability
        file: container-networking-ci/tasks/test-scalability.yml
        params:
          ENVIRONMENT_NAME: toque
      - task: emit-datadog-test-stop
        file: container-networking-ci/tasks/emit-datadog-event.yml
        params:
          TITLE: test_end
          TEXT: test_end
          PRIORITY: normal
          AWS_ENV: toque.c2c.cf-app.com
          DATADOG_API_KEY: {{datadog_api_key}}
      - task: commit-stats
        file: container-networking-ci/tasks/commit-new-file.yml
        input_mapping:
          input_repo: toque-stats
          source: network-stats
        output_mapping: {output_repo: stats_output}
        params:
          SOURCE_FILE: stats.json
          DEST_SUFFIX: json
      - put: toque-stats
        params: {repository: stats_output}

##### Human-triggered utilities
  - name: delete-deployment-pickelhelm-cf
    public: true
    serial_groups: [pickelhelm]
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{pickelhelm-bosh-host}}
          BOSH_USER: {{pickelhelm-bosh-user}}
          BOSH_PASSWORD: {{pickelhelm-bosh-password}}
          DEPLOYMENT_NAME: cf
  - name: delete-deployment-mitre-cf
    public: true
    serial_groups: [mitre]
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{mitre-bosh-host}}
          BOSH_USER: {{mitre-bosh-user}}
          BOSH_PASSWORD: {{mitre-bosh-password}}
          DEPLOYMENT_NAME: cf
  - name: delete-deployment-toque-cf
    public: true
    serial_groups: [toque]
    plan:
      - get: container-networking-ci
      - task: delete-deployment
        file: container-networking-ci/tasks/delete-deployment.yml
        params:
          BOSH_TARGET: {{toque-bosh-host}}
          BOSH_USER: {{toque-bosh-user}}
          BOSH_PASSWORD: {{toque-bosh-password}}
          DEPLOYMENT_NAME: cf

  - name: netman-shipit
    serial_groups: [version]
    plan:
    - do:
      - aggregate:
        - get: container-networking-deployments
        - get: container-networking-ci
        - get: version
          params:
            bump: final
          passed: [mitre-cats]
        - get: netman-release
          resource: cf-networking-dev
          params:
            fetch: [master]
            submodules: none
          passed: [mitre-cats]
        - get: cf-deployment
          passed: [mitre-cats]
        - get: netman-tarball
          passed: [mitre-cats]
      - task: shipit
        file: container-networking-ci/tasks/shipit.yml
      - task: build-cli
        file: container-networking-ci/tasks/netman-build-cli.yml
      - put: version
        params: {file: version/number}
      - put: cf-networking-master
        params:
          repository: release/master
          tag: version/number
          tag_prefix: v
      - put: netman-tarball
        params:
          from: final-release/netman-([^/]*).tgz
          to: releases/
      - task: build-release-notes
        file: container-networking-ci/tasks/build-release-notes.yml
      - put: cf-networking-github-release
        params:
          name: version/number
          tag: version/number
          body: release-notes/notes.md
          tag_prefix: v
          globs:
          - final-release/netman-*.tgz
          - binaries/network-policy-plugin-*

  # bump minor version (i.e. 0.1.0 -> 0.2.0)
  - name: netman-bump-minor-version
    serial_groups: [version]
    plan:
    - aggregate:
      - get: version
        trigger: true
        passed: [netman-shipit]
        params: {bump: minor, pre: rc}
    - put: version
      params: {file: version/number}

  # merge master back to develop
  - name: netman-merge-master
    plan:
    - do:
      - aggregate:
        - get: container-networking-ci
        - get: cf-networking-master
          params:
            submodules: none
            fetch: [develop]
          passed: [netman-shipit]
          trigger: true
        - get: cf-networking-dev
          params: {submodules: none}
      - task: merge-master
        file: container-networking-ci/tasks/merge-master.yml
      - put: cf-networking-dev
        params: {repository: release-merged}

  # versioning
  - name: patch-bump
    serial_groups: [version]
    plan:
    - get: version
      params: {bump: patch}
    - put: version
      params: {file: version/number}

  - name: minor-bump
    serial_groups: [version]
    plan:
    - get: version
      params: {bump: minor}
    - put: version
      params: {file: version/number}

  - name: major-bump
    serial_groups: [version]
    plan:
    - get: version
      params: {bump: major}
    - put: version
      params: {file: version/number}
