groups:
- name: service-discovery
  jobs:
  - unit-tests

resources:
  - name: cf-networking-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-networking-ci
  - name: service-discovery-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/service-discovery-release

jobs:
  - name: unit-tests
    plan:
      - aggregate:
          - get: cf-networking-ci
          - get: service-discovery-release
            trigger: true
      - task: unit-tests
        file: cf-networking-ci/tasks/service-discovery/test-unit.yml
