groups:
- name: service-discovery
  jobs:
  - unit-tests
  - acceptance-tests
  - ushanka-deploy
- name: ushanka
  jobs:
  - ushanka-bbl-up
  - ushanka-bbl-destroy
  - ushanka-deploy

resources:
  - name: cf-networking-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-networking-ci
  - name: service-discovery-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/service-discovery-release
  - name: bosh-dns-release
    type: git
    source:
      uri: https://github.com/cf-container-networking/bosh-dns-release
      branch: wip-http-json-spike
  - name: capi-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/capi-release
      branch: master
  - name: diego-release
    type: git
    source:
      uri: https://github.com/cloudfoundry/diego-release
      branch: develop
  - name: cf-deployment-concourse-tasks
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
      branch: master
  - name: cf-networking-deployments
    type: git
    source:
      uri: "git@github.com:cloudfoundry/cf-networking-deployments.git"
      branch: master
      private_key: {{cf-networking-deployments-push-key}}
  - name: cf-deployment
    type: git
    source:
      branch: release-candidate
      uri: https://github.com/cloudfoundry/cf-deployment.git
  - name: cf-networking-dev
    type: git
    source:
      uri: git@github.com:cloudfoundry/cf-networking-release.git
      branch: develop
      ignore_paths:
        - docs
      private_key: {{cf-networking-deploy-key}}

jobs:
  - name: unit-tests
    plan:
      - aggregate:
          - get: cf-networking-ci
          - get: service-discovery-release
            trigger: true
      - task: unit-tests
        file: cf-networking-ci/tasks/service-discovery/test-unit.yml

  - name: acceptance-tests
    plan:
      - aggregate:
          - get: cf-networking-ci
          - get: bosh-dns-release
            trigger: true
          - get: service-discovery-release
            passed: [unit-tests]
            trigger: true
      - task: acceptance-tests
        privileged: true
        file: cf-networking-ci/tasks/service-discovery/test-acceptance.yml

  - name: ushanka-bbl-up
    serial_groups: [ushanka]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
      - task: bbl-up
        file: cf-deployment-concourse-tasks/bbl-up/task.yml
        params:
          BBL_GCP_SERVICE_ACCOUNT_KEY: ../gcp/service-account.key.json
          BBL_GCP_PROJECT_ID: cf-container-networking-gcp
          BBL_GCP_REGION: us-east1
          BBL_GCP_ZONE: us-east1-b
          BBL_STATE_DIR: environments/ushanka/
          BBL_IAAS: gcp
          BBL_LB_CERT: {{ushanka-lb-cert}}
          BBL_LB_KEY: {{ushanka-lb-key}}
          LB_DOMAIN: ushanka.c2c.cf-app.com
          BBL_ENV_NAME: ushanka
          OPS_FILES: local-dns.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          ops-files: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-bbl-state
            rebase: true

  - name: ushanka-bbl-destroy
    serial_groups: [ushanka]
    plan:
      - aggregate:
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
      - task: bbl-destroy
        file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
        params:
          BBL_STATE_DIR: environments/ushanka/
        input_mapping:
          bbl-state: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-bbl-state
            rebase: true

  - name: ushanka-deploy
    serial_groups: [ushanka]
    plan:
      - aggregate:
          - get: cf-networking-ci
          - get: cf-deployment-concourse-tasks
          - get: cf-networking-deployments
          - get: cf-deployment
            trigger: true
          - get: cf-networking-dev
          - get: service-discovery-release
            trigger: true
            passed: [unit-tests]
          - get: bosh-dns-release
            trigger: true
      - task: upload-stemcell
        file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
        params:
          BBL_STATE_DIR: environments/ushanka/
        input_mapping:
          bbl-state: cf-networking-deployments
      - task: collect-ops-files
        file: cf-networking-ci/tasks/collect-ops-files.yml
        params:
          ENVIRONMENT_NAME: ushanka
        input_mapping:
          cf-networking-release: cf-networking-dev
          deployments-repo: cf-networking-deployments
      - task: upload-local-capi-release
        file: cf-networking-ci/tasks/service-discovery/upload-local-release.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          local-release: capi-release
        params:
          BBL_STATE_DIR: environments/ushanka/
      - task: upload-local-diego-release
        file: cf-networking-ci/tasks/service-discovery/upload-local-release.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          local-release: diego-release
        params:
          BBL_STATE_DIR: environments/ushanka/
      - task: upload-local-bosh-dns-releases
        file: cf-networking-ci/tasks/service-discovery/upload-local-release.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          local-release: bosh-dns-release
        params:
          BBL_STATE_DIR: environments/ushanka/
      - task: upload-local-service-discovery-releases
        file: cf-networking-ci/tasks/service-discovery/upload-local-release.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          local-release: service-discovery-release
        params:
          BBL_STATE_DIR: environments/ushanka/
      - task: deploy-cf
        file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
        params:
          BBL_STATE_DIR: environments/ushanka/
          SYSTEM_DOMAIN: ushanka.c2c.cf-app.com
          OPS_FILES: use-compiled-releases.yml datadog.yml cf-networking.yml opsfile.yml
          VARS_STORE_FILE: environments/ushanka/vars-store.yml
        input_mapping:
          bbl-state: cf-networking-deployments
          release: cf-networking-dev
          vars-files: cf-networking-deployments
          vars-store: cf-networking-deployments
        ensure:
          put: cf-networking-deployments
          params:
            repository: updated-vars-store
            rebase: true
      - task: bosh-cleanup
        file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
        params:
          BBL_STATE_DIR: environments/ushanka/
          CLEAN_ALL: false
        input_mapping:
          bbl-state: cf-networking-deployments
