groups:
- name: service-discovery
  jobs:
  - unit-tests
  - acceptance-tests

resources:
  - name: cf-networking-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-networking-ci
  - name: service-discovery-release
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/service-discovery-release
  - name: bosh-dns-release
    type: git
    source:
      uri: https://github.com/cf-container-networking/bosh-dns-release
      branch: wip-http-json-spike

jobs:
  - name: unit-tests
    plan:
      - aggregate:
          - get: cf-networking-ci
          - get: service-discovery-release
            trigger: true
      - task: unit-tests
        file: cf-networking-ci/tasks/service-discovery/test-unit.yml

  - name: acceptance-tests
    plan:
      - aggregate:
          - get: cf-networking-ci
          - get: bosh-dns-release
            trigger: true
          - get: service-discovery-release
            passed: [unit-tests]
            trigger: true
      - task: acceptance-tests
        privileged: true
        file: cf-networking-ci/tasks/service-discovery/test-acceptance.yml
